### ISSUE TITLE
Started getting "User does not have a valid session" message

### ISSUE THREAD

**Issue by grzechj** [arnesongit/repository.arneson#2]
Since couple days TIDAL2 plugin stopped to work on all my Kodi instances. I keep getting 401 "User does not have a valid session" error. Account is valid and can access TIDAL content using web browser or Android application. Logs below:

16:30:08.909 T:1858073504   ERROR: [TIDAL2] tidalapi: https://api.tidal.com/v1/users/37668340/favorites/albums?limit=9999&countryCode=PL
16:30:08.912 T:1858073504   ERROR: [TIDAL2] tidalapi: User does not have a valid session
16:30:08.914 T:1858073504   ERROR: Traceback (most recent call last):
16:30:08.914 T:1858073504   ERROR:   File "/storage/.kodi/addons/plugin.audio.tidal2/addon.py", line 748, in <module>
16:30:08.917 T:1858073504   ERROR:     plugin.run()
16:30:08.917 T:1858073504   ERROR:   File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
16:30:08.918 T:1858073504   ERROR:     self._dispatch(path)
16:30:08.919 T:1858073504   ERROR:   File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
16:30:08.919 T:1858073504   ERROR:     view_func(**kwargs)
16:30:08.919 T:1858073504   ERROR:   File "/storage/.kodi/addons/plugin.audio.tidal2/addon.py", line 497, in favorites
16:30:08.920 T:1858073504   ERROR:     items = session.user.favorites.get(content_type, limit=100 if content_type == 'videos' else 9999)
16:30:08.920 T:1858073504   ERROR:   File "/storage/.kodi/addons/plugin.audio.tidal2/resources/lib/koditidal2.py", line 418, in get
16:30:08.922 T:1858073504   ERROR:     items = TidalFavorites.get(self, content_type, limit=limit)
16:30:08.922 T:1858073504   ERROR:   File "/storage/.kodi/addons/plugin.audio.tidal2/resources/lib/koditidal.py", line 1270, in get
16:30:08.927 T:1858073504   ERROR:     items = Favorites.get(self, content_type, limit=limit)
16:30:08.927 T:1858073504   ERROR:   File "/storage/.kodi/addons/plugin.audio.tidal2/resources/lib/tidalapi/__init__.py", line 657, in get
16:30:08.931 T:1858073504   ERROR:     items = self._session._map_request(self._base_url + '/%s' % content_type, params={'limit': limit if content_type <> 'videos' else min(limit, 100)}, ret=content_type)
16:30:08.931 T:1858073504   ERROR:   File "/storage/.kodi/addons/plugin.audio.tidal2/resources/lib/tidalapi/__init__.py", line 365, in _map_request
16:30:08.931 T:1858073504   ERROR:     r = self.request(method, url, params=params, data=data, headers=headers)
16:30:08.932 T:1858073504   ERROR:   File "/storage/.kodi/addons/plugin.audio.tidal2/resources/lib/tidalapi/__init__.py", line 163, in request
16:30:08.932 T:1858073504   ERROR:     r.raise_for_status()
16:30:08.932 T:1858073504   ERROR:   File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 939, in raise_for_status
16:30:08.935 T:1858073504   ERROR:     raise HTTPError(http_error_msg, response=self)
16:30:08.935 T:1858073504   ERROR: HTTPError: 401 Client Error: Unauthorized for url: https://api.tidal.com/v1/users/37668340/favorites/albums?limit=9999&countryCode=PL
16:30:09.245 T:1945483728   ERROR: GetDirectory - Error getting plugin://plugin.audio.tidal2/favorites/albums
16:30:09.246 T:1945483728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.tidal2/favorites/albums) failed

**Comment by grzechj** [comment]
Appears that logoff and login resolves the problem.

**Comment by NielsMayer** [comment]
I too had this problem and also solved with logout, restart kodi, login.

I believe it recurs if other tidal music service logins occur afterwards, either from other kodi instances using same account, or from android apps with tidal support like "usb audio player pro" ...
